apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 10
  template:
    metadata: 
      name: myapp
      labels: 
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx
